# -*- coding: utf-8 -*-
"""setupSample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b7FOY_fBwZaHvDKBPK-KMczudH6kaIzr
"""

print("hello")

from google.colab import drive
drive.mount('/content/drive/')

!ls "/content/drive/My Drive/GoogleColab"

!pip install -q keras

!python3 "/content/drive/My Drive/GoogleColab/mnist_cnn.py"

!wget https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/Titanic.csv -P "/content/drive/My Drive/GoogleColab"

import pandas as pd
titanic = pd.read_csv("/content/drive/My Drive/GoogleColab/Titanic.csv")
titanic.head(5)

!git clone https://github.com/wxs/keras-mnist-tutorial.git

!mv keras-mnist-tutorial drive/MyDrive/GoogleColab/keras-mnist-tutorial

!pip install -q keras
import keras

!pip3 install torch torchvision

!apt install libnvrtc8.0
!pip install mxnet-cu80

!apt-get -qq install -y libsm6 libxext6 && pip install -q -U opencv-python
import cv2

!apt-get -qq install -y graphviz && pip install -q pydot
import pydot

!apt-get -qq install -y libarchive-dev && pip install -q -U libarchive
import libarchive

from tensorflow.python.client import device_lib
device_lib.list_local_devices()

!cat /proc/meminfo

!cat /proc/cpuinfo

import os
os.chdir("drive/MyDrive/GoogleColab")

ls